import React from 'react';
import {StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'space-evenly',
    alignItems: 'center',
    backgroundColor: '#fefefe',
  },
  favBtn: {
    width: '100%',
    height: '8%',
    minHeight: 40,
    backgroundColor: '#999999',
    marginVertical: 5,
    justifyContent: 'center',
  },
  favBtnImage: {
    position: 'relative',
    width: '100%',
    height: '100%',
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    opacity: 0.5,
  },
  favBtnText: {
    color: '#222222',
    position: 'absolute',
    fontSize: 26,
    fontFamily: 'KronaOne',
    alignSelf: 'center',
  },
  categoryContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#fefefe',
    position: 'relative',
  },
  favEmptyTxt: {
    fontSize: 16,
    fontWeight: 'bold',
  },
  recipeImg: {
    width: '100%',
    height: 300,
    position: 'relative',
  },
  recipeIconArea: {
    width: '100%',
    height: 45,
    position: 'absolute',
    bottom: 0,
    borderBottomLeftRadius: 12,
    borderBottomRightRadius: 12,
    flexDirection: 'row',
    flex: 1,
    justifyContent: 'flex-end',
    alignItems: 'center',
    paddingRight: 6,
    marginBottom: 2,
  },
  recipeIcons: {
    marginHorizontal: 10,
    backgroundColor: '#fefefe',
    borderRadius: 50,
    padding: 4,
    opacity: 1,
  },
  recipeTitle: {
    fontSize: 26,
    fontWeight: 'bold',
    textAlign: 'center',
    backgroundColor: '#fefefe',
  },
  recipeTextContainer: {
    marginBottom: 20,
  },
  recipeYield: {
    alignSelf: 'center',
    fontSize: 18,
    marginTop: 5,
  },
  recipeDiscTitle: {
    marginLeft: 10,
    marginVertical: 10,
    fontSize: 18,
    fontWeight: 'bold',
  },
  recipeDisc: {
    fontSize: 14,
    marginHorizontal: 12,
  },
  cardContainer: {
    width: '90%',
    height: 300,
    borderRadius: 15,
    justifyContent: 'space-between',
    alignItems: 'center',
    alignSelf: 'center',
    borderWidth: 2,
    margin: 5,
    overflow: 'hidden',
  },
  cardTitle: {
    backgroundColor: '#fefefe',
    margin: 5,
    fontWeight: 'bold',
    fontSize: 16,
    fontFamily: 'KronaOne',
  },
  cardImg: {
    width: '100%',
    height: 120,
  },
  cardImgLoading: {
    width: '100%',
    height: 100,
    position: 'absolute',
  },
  cardDis: {
    margin: 5,
  },
  cardBtn: {
    backgroundColor: '#959595',
    width: '100%',
    height: 35,
    alignItems: 'center',
    borderBottomLeftRadius: 13,
    borderBottomRightRadius: 13,
    justifyContent: 'center',
  },
  cardBtnTxt: {
    color: '#fefefe',
    fontSize: 16,
    fontWeight: 'bold',
  },
  loadingArea: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    position: 'relative',
  },
  homeItem: {
    width: '90%',
    height: '20%',
    position: 'relative',
    marginVertical: 5,
    borderRadius: 15,
    borderWidth: 2,
    justifyContent: 'center',
  },
  homeItemImg: {
    position: 'relative',
    width: '100%',
    height: '100%',
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 14,
  },
  homeLoadingImg: {
    width: '50%',
    height: '78%',
    position: 'absolute',
    alignSelf: 'center',
  },
  homeItemText: {
    color: '#fefefe',
    position: 'absolute',
    fontSize: 38,
    textShadowColor: '#202020',
    textShadowRadius: 20,
    fontFamily: 'KronaOne',
    alignSelf: 'center',
  },
});
